# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wrestling With Johners
email: wrestlingwtihjohners@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Pro Wrestling podcast with news, reviews and debate from WWE, NXT, NXT:UK, AEW, NJPW, Indy Wrestling and so much more. Listen to Wrestling With Johners on Apple Podcasts, Google Podcasts, Spotify, Podbean, Podcast Addict, Castbox, YouTube or wherever you get your podcasts.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: withjohners_pod
facebook_group_id: "2235004610046988"
instagram_username: wrestlingwithjohners
#github_username: wrestlingwithjohners
apple_podcast_id: "1442108418"
apple_username: wrestling-with-johners
spotify_show_id: 0s5QReHi6jMO3Kmm1I2yCd
youtube_channel_id: UC2P51c6szAyElgFPdKiqzEg
twitch_channel_id: wrestlingwithjohnerspod
anchor_username: wrestlingwithjohners

author: John Scott

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-seo-tag
  
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: "/page/:num/"
  limit: 0
  sort_reverse: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - post_updater/

# Categories
permalink: pretty

# Collections
collections:
 authors:
  output: true
  
# Variables
default-background: /img/default-background.png

ads:
  thirteenTen:
    enabled: false

defaults:
  -
    scope:
      path: "podcasts/page/*/"
    values:
      sitemap: false
  -
    scope:
      path: "articles/page/*/"
    values:
      sitemap: false
  -
    scope:
      path: "news/page/*/"
    values:
      sitemap: false
  -
    scope:
      path: "interviews/page/*/"
    values:
      sitemap: false

