name: Publish Site

on: [workflow_dispatch, push]

jobs:
  hugo_build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.121.2

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PUBLISH_PRIVATE_KEY }}

      - name: Checkout source branch for building Pages
        uses: actions/checkout@v4
        with:
          path: 'source'
          submodules: 'recursive'

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Hugo Build
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          cd source/prebuild
          hugo --gc --minify
          cd ../
          hugo --gc --minify

      - name: Clone repo for GitHub Pages
        run: git clone --depth 1 git@github.com:wrestling-with-johners/wrestling-with-johners.github.io.git published

      - name: Copy built site files into Git branch
        run: |
          rm -rf published/*
          cp -a source/public/. published
          touch published/.nojekyll

      - name: Add, Commit then Push
        run: |
          cd published
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -A .
          if [ "$(git status --porcelain)" ]; then
            echo "Commit required"
            git commit -m 'Updates compiled site files'
            git push --quiet origin master
          else
            echo "No commit required"
          fi
