name: Update Posts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'


jobs:
  update_posts:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p $HOME/.ssh/
          echo "${{ secrets.UPDATE_POSTS_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan github.com >> $HOME/.ssh/known_hosts

      - name: Checkout source branch
        run: |
          mkdir source
          git clone ssh://git@github.com/wrestling-with-johners/website-source.git source

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r source/post_updater/requirements.txt
          
      - name: Update Wrestling With Johners Posts
        run: |
          ./source/post_updater/generate_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output source/_posts/wrestling-with-johners-podcast/ \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --spotifyid ${{ secrets.SPOTIFY_CLIENT_ID }} \
          --spotifysecret ${{ secrets.SPOTIFY_CLIENT_SECRET }} \
          --youtubeplaylistid UU2P51c6szAyElgFPdKiqzEg \
          --spotifyshowid 0s5QReHi6jMO3Kmm1I2yCd \
          --applepodcastid 1442108418 \
          --category podcasts \
          --author john
           
      - name: Update Turnbuckle Arms Posts
        run: |
          ./source/post_updater/generate_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output source/_posts/turnbuckle-arms-podcast/ \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --spotifyid ${{ secrets.SPOTIFY_CLIENT_ID }} \
          --spotifysecret ${{ secrets.SPOTIFY_CLIENT_SECRET }} \
          --youtubeplaylistid UUYDa5yBbWML_3LzTVCBraDQ \
          --spotifyshowid 3tyyGlrWUfCi4AwRrHkADd \
          --applepodcastid 1519669566 \
          --category turnbuckle-arms-podcast \
          --author turnbuckle-arms-podcast

      - name: Update The Chokeslam Wrestling Report
        run: |
          ./source/post_updater/generate_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output source/_posts/chokeslam-wrestling-report/ \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --spotifyid ${{ secrets.SPOTIFY_CLIENT_ID }} \
          --spotifysecret ${{ secrets.SPOTIFY_CLIENT_SECRET }}  \
          --youtubeplaylistid UU6qyBp_AFQsaXAIgIfhEzNw \
          --spotifyshowid 0L3VJhyCb06ZXTkyUm88DR \
          --applepodcastid 1471778112 \
          --category chokeslam-wrestling-report \
          --author chokeslam-wrestling-report

      - name: Update Kyle's Wrestling
        run: |
          ./source/post_updater/generate_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output source/_posts/kyles-wrestling/ \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --youtubeplaylistid UUcKE7J5v87qW-ZqszbLJW2A \
          --category kyles-wrestling \
          --author kyles-wrestling

      - name: Update Pull Up A Seat
        run: |
          ./source/post_updater/generate_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output source/_posts/pull-up-a-seat/ \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --spotifyid ${{ secrets.SPOTIFY_CLIENT_ID }} \
          --spotifysecret ${{ secrets.SPOTIFY_CLIENT_SECRET }}  \
          --youtubeplaylistid UUH8dpQicvMaZisqSKtCHRjQ \
          --spotifyshowid 62kYSVvKtd1sXjUme1LZI2 \
          --category pull-up-a-seat \
          --author matt-bayliss

      - name: Update Pro Wrestling Tonight
        run: |
          ./source/post_updater/generate_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output source/_posts/pro-wrestling-tonight/ \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --youtubeplaylistid UU0U0XXugwAMNUWIYKh9iK7w \
          --category pro-wrestling-tonight \
          --author chicagoland-championship-wrestling

      - name: Update The Kurt Johansson Show
        run: |
          ./source/post_updater/generate_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output source/_posts/kurt-johansson-show/ \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --youtubeplaylistid UUcoJBKF4zD1p6FR7tKRQbKw \
          --category kurt-johansson-show \
          --author kurt-johansson

      - name: Update Work The Left Side Podcast
        run: |
          ./source/post_updater/generate_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output source/_posts/work-the-left-side-podcast/ \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --youtubeplaylistid UU1hrk8NkrIXjqKniLiqeBeQ \
          --category work-the-left-side-podcast \
          --author nik-towers

      - name: Update The Power Hour
        run: |
          ./source/post_updater/generate_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output source/_posts/power-hour/ \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --youtubeplaylistid UUnDMxFgnMQUQdSDQSQOYwnw \
          --category power-hour \
          --author power-hour

      - name: Add, Commit then Push
        run: |
          cd source
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -A .
          if [ "$(git status --porcelain)" ]; then
            echo "Commit required"
            git commit -m 'Updated posts'
            git push --quiet origin master
          else
            echo "No commit required"
          fi
