name: Update Posts

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update_posts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v2
        with:
          path: 'source'

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r source/post_updater/requirements.txt
          
      - name: Update Posts
        run: |
           ./source/post_updater/generate_posts.py --mindate "$(date -d "yesterday" '+%Y-%m-%d')" --output source/_posts/ --youtubekey ${{ secrets.YOUTUBE_API_KEY }} --spotifyid ${{ secrets.SPOTIFY_CLIENT_ID }} --spotifysecret ${{ secrets.SPOTIFY_CLIENT_SECRET }}

      - name: Add, Commit then Push
        env:
          GITHUB_TOKEN: ${{ secrets. PATNAME }}
        run: |
          cd source
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -A .
          if [ "$(git status --porcelain)" ]; then
            echo "Commit required"
            git commit -m 'Updated posts'
            git push --quiet origin master
          else
            echo "No commit required"
          fi
