name: Update Posts

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */1 * * *'


jobs:
  update_posts:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p $HOME/.ssh/
          echo "${{ secrets.UPDATE_POSTS_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan github.com >> $HOME/.ssh/known_hosts

      - name: Checkout source branch
        run: |
          mkdir source
          git clone --recurse-submodules ssh://git@github.com/wrestling-with-johners/website-source.git source
          cd source
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          cd source
          python -m pip install --upgrade pip
          PIP_CONSTRAINT=./post-updater/cython_constraint.txt pip install -r post-updater/requirements.txt --no-cache-dir

      - name: Update All Podcasts
        run: |
          cd source
          ./post-updater/generate_podcast_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output content/podcasts/ \
          --podcastsfile prebuild/data/podcasts.yml \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --spotifyid ${{ secrets.SPOTIFY_CLIENT_ID }} \
          --spotifysecret ${{ secrets.SPOTIFY_CLIENT_SECRET }}

      - name: Update All Promotions
        run: |
          cd source
          ./post-updater/generate_podcast_posts.py \
          --mindate "$(date -d "yesterday" '+%Y-%m-%d')" \
          --output content/ \
          --podcastsfile prebuild/data/promotions.yml \
          --youtubekey ${{ secrets.YOUTUBE_API_KEY }} \
          --spotifyid ${{ secrets.SPOTIFY_CLIENT_ID }} \
          --spotifysecret ${{ secrets.SPOTIFY_CLIENT_SECRET }}

      - name: Add, Commit, then Push Main
        run: |
          cd source
          git add -A .
          if [ "$(git status --porcelain)" ]; then
            echo "Commit required"
            git commit -m 'Updated posts'
            git push --quiet origin master
          else
            echo "No commit required"
          fi
